### ISSUE TITLE
How to deal with git translations

### ISSUE THREAD

**Issue by kgaut** [niden/Git-Pre-Commit-Hook-for-certain-words#1]
On my ubuntu, Git is translated to french, so the output of git status is "modifié" instead of "modified"

I tried to change the command to add "modifié" and "ajouté" (as for "added")

```
LIST=$(git status | grep -e '\#.*\(modified\|added\|modifié\|ajouté\)')
```

But it seems like there's a problem with accentuated chars... 

from my terminal i tried 

```
git status | grep -e '\#.*\(modifié\)'
git status | grep -e '\#.*\(modifi\)'
```

without success.

Do you have any idea ? 

Cheers.

**Comment by niden** [comment]
I have never used accented characters before in that manner. However this might be able to help

http://superuser.com/questions/218825/using-find-or-grep-to-locate-filenames-with-accented-characters-from-a-different/218831#218831

**Comment by kindziora** [comment]
@kgaut for me it worked changing the grep and the git status:
e.g
`git status --v | grep -e ".*modifié.*\|.*hinzugefügt.*"`

as my output did not begin with "#", also mention to to change the regex to something more relying, because mine is to greedy

**Comment by kgaut** [comment]
I ended up switch git to english (not only because of this issue) But will try with your regexp.

cheers.

**Comment by niden** [comment]
Happy that you found a solution.
