### ISSUE TITLE
Avoid false positive

### ISSUE THREAD

**Issue by fvromera** [niden/Git-Pre-Commit-Hook-for-certain-words#3]
I think that your code:

`ERRORS=$(grep "${checks[$index]}" $ROOT_DIR$file >&1)`

must to be:

`ERRORS=$(grep "\b${checks[$index]}\b" $ROOT_DIR$file >&1)`

to avoid false positive and check only complete words, if not you detect words like ingredient, died, dielectric, etc. that contains the word "die"

**Comment by niden** [comment]
@fvromera Thank you so much for this. I made the necessary change

https://github.com/niden/Git-Pre-Commit-Hook-for-certain-words/commit/5f11461a6c76bb17e2da5ebb302290fe6c94b3fa

**Comment by niden** [comment]
Closing this.
